models/__init__.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


def reset_database():
    from models.light import Light
    db.drop_all()
    db.create_all()

models/light.py
from app import db


class Light(db.Model):
    name = db.Column(db.String(80), unique=True, nullable=False)
    def __repr__(self):
        return '<Light %r>' % self.name


class Scene:
    pass

app.py
from flask import render_template, Blueprint, Flask
import logging.config

from livereload import Server

import settings

from controllers.endpoints.lights import ns as lights_namespace
from controllers.endpoints.camera import ns as camera_namespace
from controllers.endpoints.action import ns as action_namespace
from controllers.restplus import api
from models import db
from pages.home import home
from pages.lights import lights
from pages.camera import camera
from pages.action import action

app = Flask(__name__)
logging.config.fileConfig('logging.conf')
log = logging.getLogger(__name__)


def configure_app(flask_app):
    flask_app.config['SERVER_NAME'] = settings.FLASK_SERVER_NAME
    flask_app.config['SQLALCHEMY_DATABASE_URI'] = settings.SQLALCHEMY_DATABASE_URI
    flask_app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = settings.SQLALCHEMY_TRACK_MODIFICATIONS
    flask_app.config['SWAGGER_UI_DOC_EXPANSION'] = settings.RESTPLUS_SWAGGER_UI_DOC_EXPANSION
    flask_app.config['RESTPLUS_VALIDATE'] = settings.RESTPLUS_VALIDATE
    flask_app.config['RESTPLUS_MASK_SWAGGER'] = settings.RESTPLUS_MASK_SWAGGER
    flask_app.config['ERROR_404_HELP'] = settings.RESTPLUS_ERROR_404_HELP
    flask_app.config['TEMPLATES_AUTO_RELOAD'] = True
    flask_app.config['EXPLAIN_TEMPLATE_LOADING'] = True



def initialize_app(flask_app):
    configure_app(flask_app)

    blueprint = Blueprint('api', __name__, url_prefix='/api')

    api.init_app(blueprint)
    api.add_namespace(lights_namespace)
    api.add_namespace(camera_namespace)
    api.add_namespace(action_namespace)

    flask_app.register_blueprint(blueprint)

    flask_app.register_blueprint(home, url_prefix='/')
    flask_app.register_blueprint(lights, url_prefix='/lights')
    flask_app.register_blueprint(camera, url_prefix='/camera')
    flask_app.register_blueprint(action, url_prefix='/action')

    db.init_app(flask_app)


def main():
    initialize_app(app)
    log.info('>>>>> Starting development server at http://{}/api/ <<<<<'.format(app.config['SERVER_NAME']))
    server = Server(app.wsgi_app)
    server.serve(host='0.0.0.0', port=5000)

    app.run(debug=True, host='0.0.0.0', port=5000)


if __name__ == '__main__':
    main()

controllers/hue.py
import colorsys

from flask_restful import Resource, reqparse
from flask import jsonify, json
from phue import Bridge
import ast


class HueController(Resource):

    def __init__(self):
        self._BRIDGE_IP = "10.1.1.20"
        self._bridge = Bridge(self._BRIDGE_IP)
        self._lights = self._bridge.get_light_objects('name')

    def __hex2rgb(self, hex):
        return tuple(int(hex[i:i + 2], 16) for i in (0, 2, 4))

    def _execute_recipe(self, light, recipe):
        if light in self._lights:
            l = self._lights[light]

            l.on = recipe["on"]
            l.brightness = recipe["brightness"] or l.brightness

            # set colour
            r = recipe['rgb'] if recipe['rgb'] is not None else None
            if r is not None:
                rgb = self.__hex2rgb(r)
                h, s, v = colorsys.rgb_to_hsv(*rgb)
                l.hue = h * 65535
                l.sat = s * 255
                l.bri = v


class RecipeController(Resource):
    def get(self):
        pass

    def post(self):
        pass


class ExecuteRecipeController(HueController):
    def post(self):
        parser = reqparse.RequestParser()
        parser.add_argument('mode', type=str, location='json')

        args = parser.parse_args()
        mode = ast.literal_eval(args['mode'])

        for k, v in mode.items():
            self._execute_recipe(k, v)


class ModeController(HueController):
    MODES = {
        "morning": {
        },
        "evening": {
            "description": "Evening Time",
            "modes": {
                "Living Room": {
                    "on": True,
                    "brightness": 110,
                    "colour": "red"
                }, "Penny": {
                    "status": "off",
                    "brightness": 110,
                    "colour": "red"
                }, "Hallway": {
                    "status": "off",
                    "brightness": 110,
                    "colour": "red"
                }
            }
        },
        "night": {

        }
    }

    def post(self):
        try:
            parser = reqparse.RequestParser()
            parser.add_argument('mode', type=str, location='json')

            args = parser.parse_args()
            mode = args['mode']

            if mode in self.MODES:
                for k, v in self.MODES[mode]['modes'].items():
                    if k in self._lights:
                        light = self._lights[k]
                        light.on = v['on']

            return jsonify({"success": True})

        except Exception as e:
            print(e)

controllers/restplus.py
import logging
import traceback

from flask_restplus import Api
from sqlalchemy.orm.exc import NoResultFound

import settings

log = logging.getLogger(__name__)

api = Api(version='1.0', title='Bitchmints Home Auto API',
          description='Various home automation REST endpoints')


@api.errorhandler
def default_error_handler(e):
    message = 'An unhandled exception occurred.'
    log.exception(message)

    if not settings.FLASK_DEBUG:
        return {'message': message}, 500


@api.errorhandler(NoResultFound)
def database_not_found_error_handler(e):
    log.warning(traceback.format_exc())
    return {'message': 'A database result was required but none was found.'}, 404

pages/action/__init__.py
from flask import Blueprint

action = Blueprint('action', __name__, template_folder='templates', static_folder='static')

from . import routes

pages/action/routes.py
from flask import render_template

from . import action


@action.route('/')
def index():
    return render_template('action/index.html')

pages/camera/__init__.py
from flask import Blueprint

camera = Blueprint('camera', __name__, template_folder='templates', static_folder='static')

from . import routes

pages/camera/routes.py
from flask import render_template

from . import camera


@camera.route('/')
def index():
    return render_template('camera/index.html')

pages/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__, template_folder='templates', static_folder='static')

from . import routes

pages/home/routes.py
from flask import render_template

from . import home


@home.route('/')
def index():
    return render_template('home/index.html')

pages/lights/__init__.py
from flask import Blueprint

lights = Blueprint('lights', __name__, template_folder='templates', static_folder='static')

from . import routes

pages/lights/routes.py
from flask import render_template

from . import lights


@lights.route('/')
def index():
    return render_template('lights/index.html')

pages/action/templates/action/index.html
{% extends '_base.html' %}
{% block css %}
{% endblock %}
{% block body %}
    <h1>Hot stuff goes here</h1>
{% endblock %}
{% block scripts %}
{% endblock %}

pages/camera/templates/camera/index.html
{% extends '_base.html' %}
{% block css %}
{% endblock %}
{% block body %}
    <h1>Camera stuff goes here</h1>
{% endblock %}
{% block scripts %}
{% endblock %}

pages/home/templates/home/index.html
{% extends '_base.html' %}
{% block css %}
{% endblock %}
{% block body %}
    <h1>Home page</h1>
{% endblock %}
{% block scripts %}
{% endblock %}

pages/lights/templates/lights/index.html
{% extends '_base.html' %}
{% block css %}
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">
    <link rel="stylesheet" href="{{ url_for('lights.static', filename='css/form.css') }}">
    <link rel="stylesheet" href="{{ url_for('lights.static', filename='css/slider.css') }}">
{% endblock %}
{% block body %}
    <form class="form-horizontal">
        <fieldset>
            <legend>Select Light Parameters</legend>
            <div class="form-group">
                <label for="textinput" class="control-label col-sm-2">Light</label>
                <div class="col-sm-10">
                    <select class="selectpicker" name="lights" id="lights">
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label for="textinput" class="control-label col-sm-2">Brightness</label>
                <div class="col-sm-10">
                    <input id="brightness" type="range"
                           data-slider-id='brightness'
                           data-slider-min="0"
                           data-slider-max="255"
                           data-slider-step="1"
                           data-slider-value="50"/>
                </div>
            </div>
            <div class="form-group">
                <label for="textinput" class="control-label col-sm-2">Colour</label>
                <div class="col-sm-10">
                    <input type="color" id="colourpicker" name="colourpicker" value="#F8EB48"/>
                </div>
            </div>
        </fieldset>
        <div class="form-group">
            <div>
                <button class="btn btn-primary" name="submit" type="submit">
                    Send to Light
                </button>
            </div>
        </div>
    </form>

{% endblock %}
{% block scripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js"></script>
    <script src="{{ url_for('lights.static', filename='js/lights.js') }}"></script>
    <script src="{{ url_for('lights.static', filename='js/slider.js') }}"></script>
{% endblock %}

templates/_base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Bitchmints Home Auto Repair</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    {#    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"#}
    {#          integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">#}
    <link rel=stylesheet type=text/css
          href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/site.css') }}">
    {% block css %}
    {% endblock %}
</head>
<body>

<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">Bitch::Mints</a>
        </div>
    </div>
</nav>
</body>

<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Bitch::Mints</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li id="home_index"><a href="{{ url_for('home.index') }}">Home</a></li>
                <li id="lights_index"><a href="{{ url_for('lights.index') }}">Lights</a></li>
                <li id="camera_index"><a href="{{ url_for('camera.index') }}">Camera</a></li>
                <li id="action_index"><a href="{{ url_for('action.index') }}">Action</a></li>
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    {% block body %}{% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"
        integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"
        integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ"
        crossorigin="anonymous"></script>
{% block scripts %}
{% endblock %}

<script>
    $(document).ready(function () {
        $("#{{request.endpoint}}".replace('.', '_')).addClass("active");
    })
</script>
</body>
</html>